<?php
namespace webrise1\pdfgenerator\models;
class Certificate extends \yii\db\ActiveRecord{
    const TABLE_NAME='ext_pdf_generator_certificate';
    public function rules()
    {
        return [
            [['user_id','template_certificate_id'], 'required'],
            ['user_id', 'uniqueCertificate'],
        ];
    }
    public function uniqueCertificate($attribute, $params) {
            if($this->isNewRecord){
                $existModel = self::find()->where(['user_id'=>$this->user_id,'template_certificate_id'=>$this->template_certificate_id])->one();
                if ($existModel) {
                    $this->addError($attribute, 'У пользователя уже существует данный сертификат.');
                }
            }
    }

    public static function tableName()
    {
        return self::TABLE_NAME;
    }
    public function getTemplateCertificate(){
        return $this->hasOne(TemplateCertificate::className(),['id'=>'template_certificate_id']);
    }
    public function getUser(){
        return $this->hasOne(User::className(),['id'=>'user_id']);
    }
    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            $this->token=\Yii::$app->security->generateRandomString(64);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function attributeLabels()
    {
        return [
            'visited_at' => 'Время визита'
        ];
    }
}